eureka:
  instance:
    hostname: localhost
  client:
    discovery-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8763/eureka/
      
      
property-test:
     value: hello Girraj 
     des: test

